name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build vocab-service Docker image
      run: docker build vocab-service --file vocab-service/Dockerfile --tag vocab-service:$(date +%s)
    - name: Build notification-service Docker image
      run: docker build notification-service --file notification-service/Dockerfile --tag notification-service:$(date +%s)
